import { API_V1_URL } from '../config.js';

export class PyodideLoader {
    constructor() {
        this.pyodide = null;
        this.engine = null;
        this.moduleCache = new Map();
    }

    topoSortModules(modules) {
        const modMap = new Map();
        modules.forEach(m => modMap.set(m.id || m.name, m));
        
        const visited = new Set();
        const tempVisited = new Set();
        const sorted = [];
        
        function visit(id) {
            if (tempVisited.has(id)) {
                throw new Error(`Circular dependency detected in module: ${id}`);
            }
            if (!visited.has(id)) {
                tempVisited.add(id);
                const mod = modMap.get(id);
                if (!mod) {
                    throw new Error(`Missing module declaration for: ${id}`);
                }
                for (const dep of (mod.dependencies || [])) {
                    if (modMap.has(dep)) {
                        visit(dep);
                    } else {
                        throw new Error(`Missing module dependency: '${dep}' required by '${id}'!`);
                    }
                }
                tempVisited.delete(id);
                visited.add(id);
                sorted.push(mod);
            }
        }
        
        modules.forEach(m => {
            const modId = m.id || m.name;
            if (!visited.has(modId)) {
                visit(modId);
            }
        });
        
        return sorted;
    }

    async init(onProgress) {
        const notifyProgress = (pct, msg) => {
            if (typeof onProgress === 'function') {
                onProgress(pct, msg);
            }
        };

        try {
            notifyProgress(10, "Initializing Pyodide WebAssembly...");
            this.pyodide = await loadPyodide();
            
            notifyProgress(25, "Mounting Python System Packages...");
            await this.loadModule('shared/__init__.py', '');
            await this.loadModule('shared/engine/__init__.py', '');
            
            // 1. Fetch modules.json automatically generated by build.py
            notifyProgress(30, "Fetching Python Module Manifest...");
            const modulesRes = await fetch('assets/runtime/modules.json');
            if (!modulesRes.ok) {
                throw new Error(`Failed to fetch modules.json (Status: ${modulesRes.status})`);
            }
            const modulesData = await modulesRes.json();
            const rawModules = modulesData.modules || [];
            
            // 2. Perform topological sort for dependency resolution
            const orderedModules = this.topoSortModules(rawModules);
            const total = orderedModules.length;
            
            // 3. Load modules in order into Pyodide virtual filesystem with progress updates & caching
            for (let i = 0; i < total; i++) {
                const mod = orderedModules[i];
                const pct = 35 + Math.floor(((i + 1) / total) * 45);
                notifyProgress(pct, `Loading Python Module (${i + 1}/${total}: ${mod.filename})...`);
                
                try {
                    const code = await this.fetchTextCached(mod.path);
                    await this.loadModule(`shared/engine/${mod.filename}`, code);
                    console.log(`✓ Loaded ${mod.filename}`);
                } catch (err) {
                    const modId = mod.id || mod.name;
                    const importers = rawModules
                        .filter(m => (m.dependencies || []).includes(modId))
                        .map(m => m.filename)
                        .join(', ');
                    const importedByMsg = importers ? ` (imported by: ${importers})` : '';
                    throw new Error(`Missing module: ${mod.filename}${importedByMsg}. Details: ${err.message}`);
                }
            }

            notifyProgress(80, "Finalizing Python Path Configuration...");
            await this.pyodide.runPythonAsync(`import sys; sys.path.append('/')`);
            notifyProgress(85, "Python Engine Ready!");
        } catch (error) {
            console.error("[PyodideLoader] Automatic Initialization Error:", error);
            throw error;
        }
    }

    async fetchTextCached(url) {
        if (this.moduleCache.has(url)) {
            return this.moduleCache.get(url);
        }
        const text = await this.fetchText(url);
        this.moduleCache.set(url, text);
        return text;
    }

    async fetchText(url) {
        const res = await fetch(url);
        if (!res.ok) throw new Error(`Failed to fetch ${url} (status: ${res.status})`);
        return await res.text();
    }

    async loadModule(path, code) {
        const parts = path.split('/');
        let currentPath = '';
        for (let i = 0; i < parts.length - 1; i++) {
            currentPath += (currentPath ? '/' : '') + parts[i];
            try { this.pyodide.FS.mkdir(currentPath); } catch(e) {}
        }
        this.pyodide.FS.writeFile(path, code);
    }

    async loadLevel(levelNumOrId) {
        let jsonText = null;
        
        try {
            const apiRes = await fetch(`${API_V1_URL}/levels/${levelNumOrId}`);
            if (apiRes.ok) {
                const jsonData = await apiRes.json();
                jsonText = JSON.stringify(jsonData);
            }
        } catch (e) {
            console.log(`API fetch skipped for level ${levelNumOrId}, falling back to static runtime asset...`);
        }

        if (!jsonText) {
            let levelStr = typeof levelNumOrId === 'number' ? String(levelNumOrId).padStart(3, '0') : levelNumOrId;
            if (!levelStr.startsWith('level')) {
                levelStr = `level${levelStr}`;
            }
            jsonText = await this.fetchTextCached(`assets/runtime/levels/${levelStr}.json`);
        }

        this.pyodide.globals.set("level_json_str", jsonText);
        
        await this.pyodide.runPythonAsync(`
import json
from shared.engine.level_parser import LevelParser
level_dict = json.loads(level_json_str)
engine, metadata = LevelParser.load_from_json(level_dict)
        `);
        
        this.engine = this.pyodide.globals.get("engine");
        const meta = this.pyodide.globals.get("metadata");
        
        return meta;
    }
}

export const loader = new PyodideLoader();
